# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
    - image: circleci/golang:1.13
    working_directory: /go/src/github.com/AliyunContainerService/sgx-device-plugin
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: run tests
        command: |
          test -z $(go fmt ./...)
          go vet -asmdecl=false ./...
          go test -race -v ./...
    - run: 
        name: build image
        command: |
          make binary
          docker build -t acs/sgx-device-plugin:$CIRCLE_BUILD_NUM .
    - run:
        name: "validate lint"
        command: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0
          golangci-lint run --disable govet         
workflows:
  version: 2
  ci:
    jobs:
      - build
